version: '3.8'

services:
  ates_tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v3.2.1
    ports:
      - 8080:8080
    networks:
      - kafka
    volumes:
      - ./tyk-gateway-docker/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk-gateway-docker/apps:/opt/tyk-gateway/apps
      - ./tyk-gateway-docker/middleware:/opt/tyk-gateway/middleware
      - ./tyk-gateway-docker/certs:/opt/tyk-gateway/certs
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - ates_tyk-redis

  ates_tyk-redis:
    image: redis:5.0-alpine
    networks:
      - external
#    ports:
#      - 6379:6379

  ates_zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: ates_zookeeper
    container_name: ates_zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-2181}:${ZOOKEEPER_PORT:-2181}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT:-2181}
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - external

  ates_broker:
    image: confluentinc/cp-server:6.2.1
    hostname: ates_broker
    container_name: ates_broker
    depends_on:
      - ates_zookeeper
    restart: always
    ports:
      - "${KAFKA_PORT:-9092}:${KAFKA_PORT:-9092}"
      - "${KAFKA_JMX_PORT:-9101}:${KAFKA_JMX_PORT:-9101}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'ates_zookeeper:${ZOOKEEPER_PORT:-2181}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ates_broker:${KAFKA_BROKER_PORT:-29092},PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: ${KAFKA_JMX_PORT:-9101}
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://ates_schema-registry:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ates_broker:${KAFKA_BROKER_PORT:-29092}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - external

#  ates_schema-registry:
#    image: confluentinc/cp-schema-registry:6.2.1
#    hostname: ates_schema-registry
#    container_name: ates_schema-registry
#    depends_on:
#      - ates_broker
#    ports:
#      - "${KAFKA_SCHEMA_REGISTRY_PORT:-8081}:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: ates_schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'ates_broker:${KAFKA_BROKER_PORT:-29092}'
#      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}
#    networks:
#      - external

#  ates_connect:
#    image: cnfldemos/cp-server-connect-datagen:0.5.0-6.2.1
#    hostname: ates_connect
#    container_name: ates_connect
#    depends_on:
#      - ates_broker
#      - ates_schema-registry
#    ports:
#      - "${KAFKA_CONNECT_PORT:-8083}:${KAFKA_CONNECT_PORT:-8083}"
#    environment:
#      CONNECT_BOOTSTRAP_SERVERS: 'ates_broker:${KAFKA_BROKER_PORT:-29092}'
#      CONNECT_REST_ADVERTISED_HOST_NAME: ates_connect
#      CONNECT_REST_PORT: ${KAFKA_CONNECT_PORT:-8083}
#      CONNECT_GROUP_ID: compose-connect-group
#      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
#      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://ates_schema-registry:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}
#      # CLASSPATH required due to CC-2422
#      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-6.2.1.jar
#      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
#      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
#      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
#      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
#    networks:
#      - external

#  ates_control-center:
#    image: confluentinc/cp-enterprise-control-center:6.2.1
#    hostname: ates_control-center
#    container_name: ates_control-center
#    depends_on:
#      - ates_broker
#      - ates_schema-registry
#      - ates_connect
#      - ates_ksqldb-server
#    ports:
#      - "${KAFKA_CONTROL_CENTER_PORT:-9021}:${KAFKA_CONTROL_CENTER_PORT:-9021}"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'ates_broker:${KAFKA_BROKER_PORT:-29092}'
#      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'ates_connect:${KAFKA_CONNECT_PORT:-8083}'
#      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ates_ksqldb-server:${KAFKA_KSQL_PORT:-8088}"
#      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:${KAFKA_KSQL_PORT:-8088}"
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://ates_schema-registry:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}"
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: ${KAFKA_CONTROL_CENTER_PORT:-9021}
#    networks:
#      - external

#  ates_ksqldb-server:
#    image: confluentinc/cp-ksqldb-server:6.2.1
#    hostname: ates_ksqldb-server
#    container_name: ates_ksqldb-server
#    depends_on:
#      - ates_broker
#      - ates_connect
#    ports:
#      - "${KAFKA_KSQL_PORT:-8088}:${KAFKA_KSQL_PORT:-8088}"
#    environment:
#      KSQL_CONFIG_DIR: "/etc/ksql"
#      KSQL_BOOTSTRAP_SERVERS: "ates_broker:${KAFKA_BROKER_PORT:-29092}"
#      KSQL_HOST_NAME: ates_ksqldb-server
#      KSQL_LISTENERS: "http://0.0.0.0:${KAFKA_KSQL_PORT:-8088}"
#      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
#      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://ates_schema-registry:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}"
#      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
#      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
#      KSQL_KSQL_CONNECT_URL: "http://ates_connect:${KAFKA_CONNECT_PORT:-8083}"
#      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
#      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
#      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'
#    networks:
#      - external

#  ates_ksqldb-cli:
#    image: confluentinc/cp-ksqldb-cli:6.2.1
#    container_name: ates_ksqldb-cli
#    depends_on:
#      - ates_broker
#      - ates_connect
#      - ates_ksqldb-server
#    entrypoint: /bin/sh
#    tty: true
#    networks:
#      - external
#
#  ates_ksql-datagen:
#    image: confluentinc/ksqldb-examples:6.2.1
#    hostname: ates_ksql-datagen
#    container_name: ates_ksql-datagen
#    depends_on:
#      - ates_ksqldb-server
#      - ates_broker
#      - ates_schema-registry
#      - ates_connect
#    command: "bash -c 'echo Waiting for Kafka to be ready... && \
#                       cub kafka-ready -b ates_broker:${KAFKA_BROKER_PORT:-29092} 1 40 && \
#                       echo Waiting for Confluent Schema Registry to be ready... && \
#                       cub sr-ready ates_schema-registry ${KAFKA_SCHEMA_REGISTRY_PORT:-8081} 40 && \
#                       echo Waiting a few seconds for topic creation to finish... && \
#                       sleep 11 && \
#                       tail -f /dev/null'"
#    environment:
#      KSQL_CONFIG_DIR: "/etc/ksql"
#      STREAMS_BOOTSTRAP_SERVERS: ates_broker:${KAFKA_BROKER_PORT:-29092}
#      STREAMS_SCHEMA_REGISTRY_HOST: ates_schema-registry
#      STREAMS_SCHEMA_REGISTRY_PORT: ${KAFKA_SCHEMA_REGISTRY_PORT:-8081}
#    networks:
#      - external

#  ates_rest-proxy:
#    image: confluentinc/cp-kafka-rest:6.2.1
#    depends_on:
#      - ates_broker
#      - ates_schema-registry
#    ports:
#      - ${KAFKA_REST_PROXY_PORT:-8082}:${KAFKA_REST_PROXY_PORT:-8082}
#    hostname: ates_rest-proxy
#    container_name: ates_rest-proxy
#    environment:
#      KAFKA_REST_HOST_NAME: ates_rest-proxy
#      KAFKA_REST_BOOTSTRAP_SERVERS: 'ates_broker:${KAFKA_BROKER_PORT:-29092}'
#      KAFKA_REST_LISTENERS: "http://0.0.0.0:${KAFKA_REST_PROXY_PORT:-8082}"
#      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://ates_schema-registry:${KAFKA_SCHEMA_REGISTRY_PORT:-8081}'
#    networks:
#      - external

networks:
  external:
    name: ates_network

