update:
	curl -X GET \
      http://127.0.0.1:8080/tyk/reload \
      -H 'cache-control: no-cache' \
      -H 'postman-token: eb3eec9f-286e-175c-6b72-c0a5cd47ed2a' \
      -H 'x-tyk-authorization: foo'